name: 'Deploy yaml'
description: 'Deploys a yaml file to a Lightning instance'
inputs:
  secret_input:
    description: "OpenFN API KEY"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Project export
      uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
      env: 
        FORCE_COLOR: 0
        OPENFN_API_KEY: ${{ inputs.secret_input }}
    - run: npm install @openfn/cli
      shell: bash
    - run: openfn deploy -c config.json --no-confirm
      shell: bash
