name: 'Deploy yaml'
description: 'Deploys a yaml file to a Lightning instance'
runs:
  using: "composite"
  steps:
    - name: Checkout Project export
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        api_secret: ${{ secrets.OPENFN_API_KEY }}
      env: 
        FORCE_COLOR: 0
        OPENFN_API_KEY: ${{ inputs.api_secret }}
      with:
        node-version: 18.x
        cache: 'npm'

    - run: npm install @openfn/cli 
    - run: openfn deploy -c config.json --no-confirm
